GET https://myphonebook.fly.dev/api/persons/

###
GET https://myphonebook.fly.dev/api/persons/1

###
DELETE  https://myphonebook.fly.dev/api/persons/2

###
POST https://myphonebook.fly.dev/api/persons
Content-Type: application/json

{
    "name": "Simon",
    "number": "252624252"
}


###
GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/persons/6318379b7817c351d5362e7a

###
DELETE  http://localhost:3001/api/persons/6318379b7817c351d5362e7a

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Sjonnie",
    "number": "45"
}

###
GET http://localhost:3001/api/persons/info


###
PUT http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Sjonnie",
    "number": "12"
}

###
GET http://localhost:3001/api/persons/info